### ISSUE TITLE
Replace use of SkinTemplateNavigation hook

### ISSUE THREAD

**Issue by pppery** [WikibaseSolutions/FlexForm#41]
https://www.mediawiki.org/wiki/Manual:Hooks/SkinTemplateNavigation was removed in MediaWiki 1.41

**Comment by Designburo** [comment]
Make sure u download the correct branch.
REL1_39 uses "SkinTemplateNavigation::Universal".
That said, FlexForm officially only supports LTS versions of MediaWiki.
